#!/usr/bin/env python3
"""
Main entry point for GitClonePro CLI
"""

import sys
import argparse
import os
from pathlib import Path

from .core import GitClonePro
from .logger import setup_logger, log

def parse_arguments():
    """Parse command-line arguments"""
    parser = argparse.ArgumentParser(
        description="GitClonePro - Advanced GitHub Clone Tool",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  # Clone a single repo
  gitclone https://github.com/user/repo

  # Clone with specific branch and depth
  gitclone https://github.com/user/repo -b develop --depth 1

  # Sparse clone (only specific files/folders)
  gitclone https://github.com/user/repo --sparse src/ README.md

  # Mirror clone (bare)
  gitclone https://github.com/user/repo --mirror

  # Batch clone all repos from a user
  gitclone --owner microsoft --type public --threads 8

  # Clone private repo with token
  gitclone https://github.com/private/repo --token ghp_xxxxx

  # Use config file
  gitclone https://github.com/user/repo --config ~/my_config.yaml
        """
    )

    # Positional arguments
    parser.add_argument(
        "url",
        nargs="?",
        help="GitHub repository URL (e.g., https://github.com/user/repo)"
    )

    # Single clone options
    parser.add_argument(
        "-d", "--dest",
        help="Destination directory (default: current directory or config value)"
    )
    parser.add_argument(
        "-b", "--branch",
        help="Branch to clone (default: main or config value)"
    )
    parser.add_argument(
        "--depth", type=int,
        help="Shallow clone depth (limit history)"
    )
    parser.add_argument(
        "--mirror",
        action="store_true",
        help="Clone as mirror (bare repository)"
    )
    parser.add_argument(
        "--sparse",
        nargs="+",
        help="Sparse checkout - list of files/folders to clone"
    )
    parser.add_argument(
        "--exclude",
        nargs="+",
        help="Exclude specific files/folders from clone"
    )

    # Batch clone options
    parser.add_argument(
        "-o", "--owner",
        help="Clone all repositories from a user or organization"
    )
    parser.add_argument(
        "--type",
        choices=["all", "public", "private", "forks", "sources"],
        default="all",
        help="Repository visibility filter for batch mode"
    )
    parser.add_argument(
        "--threads", type=int,
        help="Number of parallel threads for batch cloning"
    )
    parser.add_argument(
        "--include-forks",
        action="store_true",
        help="Include forked repositories in batch"
    )

    # Authentication
    parser.add_argument(
        "--token",
        help="GitHub Personal Access Token (overrides config)"
    )
    parser.add_argument(
        "--ssh",
        action="store_true",
        help="Use SSH instead of HTTPS for cloning"
    )

    # Configuration
    parser.add_argument(
        "-c", "--config",
        help="Path to configuration file (YAML)"
    )

    # Output
    parser.add_argument(
        "-v", "--verbose",
        action="store_true",
        help="Verbose output"
    )
    parser.add_argument(
        "--quiet",
        action="store_true",
        help="Suppress all output except errors"
    )
    parser.add_argument(
        "--log-file",
        help="Path to log file"
    )

    # Utilities
    parser.add_argument(
        "--version",
        action="version",
        version=f"GitClonePro v{__import__('gitclone').__version__}"
    )
    parser.add_argument(
        "--init-config",
        action="store_true",
        help="Initialize a default configuration file"
    )

    return parser.parse_args()

def init_config():
    """Create a default config file in user's home directory"""
    config_path = Path.home() / ".gitclone_config.yaml"
    if config_path.exists():
        print(f"[!] Config already exists at {config_path}")
        return

    template = """# GitClonePro Configuration
# Generated by --init-config

# GitHub Personal Access Token
github_token: ""

# Default clone directory
clone_dir: "~/git_clones"

# Default branch
default_branch: "main"

# Retry settings
retries: 3
threads: 4
timeout: 30

# Output
verbose: true

# Logging
log_file: "~/.gitclone.log"
log_level: "INFO"

# SSH
use_ssh: false

# Security
validate_certificates: true
"""

    config_path.write_text(template)
    print(f"[+] Configuration created at {config_path}")
    print("[+] Edit this file to set your defaults")

def main():
    """Main entry point"""
    args = parse_arguments()

    # Handle --init-config
    if args.init_config:
        init_config()
        return

    # Setup logging
    logger = setup_logger(
        log_file=args.log_file,
        log_level="DEBUG" if args.verbose else "INFO" if not args.quiet else "ERROR"
    )

    # Initialize core
    try:
        core = GitClonePro(
            config_path=args.config,
            token=args.token,
            use_ssh=args.ssh,
            verbose=args.verbose,
            quiet=args.quiet
        )
    except Exception as e:
        log(f"[!] Failed to initialize: {e}", "ERROR")
        sys.exit(1)

    # Execute
    try:
        if args.owner:
            # Batch mode
            core.batch_clone(
                owner=args.owner,
                dest=args.dest,
                repo_type=args.type,
                include_forks=args.include_forks,
                threads=args.threads,
                depth=args.depth,
                mirror=args.mirror,
                branch=args.branch,
                exclude=args.exclude
            )
        elif args.url:
            # Single clone
            core.clone_single(
                url=args.url,
                dest=args.dest,
                branch=args.branch,
                depth=args.depth,
                mirror=args.mirror,
                sparse=args.sparse,
                exclude=args.exclude
            )
        else:
            print("[!] No URL or owner specified. Use --help for usage.")
            sys.exit(1)

    except KeyboardInterrupt:
        log("\n[!] Interrupted by user", "WARNING")
        sys.exit(130)
    except Exception as e:
        log(f"[!] Error: {e}", "ERROR")
        if args.verbose:
            import traceback
            traceback.print_exc()
        sys.exit(1)

if __name__ == "__main__":
    main()